-- NeuLitTrace v2 - Card 1 (Snowflake platform)
-- Run once, by hand, against the hackathon account, in numeric file order.

CREATE WAREHOUSE IF NOT EXISTS NEULIT_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NEULIT;
CREATE SCHEMA   IF NOT EXISTS NEULIT.CORE;
CREATE ROLE     IF NOT EXISTS NEULIT_APP;

GRANT USAGE ON WAREHOUSE NEULIT_WH TO ROLE NEULIT_APP;
GRANT USAGE ON DATABASE NEULIT     TO ROLE NEULIT_APP;
GRANT USAGE ON SCHEMA NEULIT.CORE  TO ROLE NEULIT_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NEULIT.CORE TO ROLE NEULIT_APP;
GRANT INSERT ON FUTURE TABLES IN SCHEMA NEULIT.CORE TO ROLE NEULIT_APP;
-- Cortex functions live on the SNOWFLAKE database
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE NEULIT_APP;
