-- NeuLitTrace v2 - Card 1. Run after 02_tables.sql. Read by /economics/* and
-- pointed at by Cortex Analyst's semantic model (semantic_model.yaml).
USE ROLE NEULIT_APP;
USE WAREHOUSE NEULIT_WH;
USE DATABASE NEULIT;
USE SCHEMA CORE;

CREATE OR REPLACE VIEW NEULIT.CORE.V_COST_BY_CALL_SITE AS
SELECT CALL_SITE, MODEL,
       COUNT(*) AS CALLS,
       SUM(PROMPT_TOKENS)     AS PROMPT_TOKENS,
       SUM(COMPLETION_TOKENS) AS COMPLETION_TOKENS,
       SUM(TOTAL_TOKENS)      AS TOTAL_TOKENS,
       SUM(COST_USD)          AS COST_USD,
       AVG(LATENCY_MS)        AS AVG_LATENCY_MS,
       SUM(IFF(DEGRADED,1,0)) AS DEGRADED_CALLS
FROM NEULIT.CORE.TOKEN_LEDGER
GROUP BY 1,2;

CREATE OR REPLACE VIEW NEULIT.CORE.V_COST_PER_REQUEST AS
SELECT REQUEST_ID, ANY_VALUE(SESSION_ID) AS SESSION_ID,
       ANY_VALUE(USER_ID) AS USER_ID,
       COUNT(*) AS LLM_CALLS,
       SUM(TOTAL_TOKENS) AS TOTAL_TOKENS,
       SUM(COST_USD)     AS COST_USD,
       MIN(OCCURRED_AT)  AS STARTED_AT
FROM NEULIT.CORE.TOKEN_LEDGER
GROUP BY REQUEST_ID;

CREATE OR REPLACE VIEW NEULIT.CORE.V_COST_BY_HOUR AS
SELECT DATE_TRUNC('hour', OCCURRED_AT) AS HOUR,
       SUM(TOTAL_TOKENS) AS TOTAL_TOKENS,
       SUM(COST_USD)     AS COST_USD,
       COUNT(DISTINCT REQUEST_ID) AS REQUESTS
FROM NEULIT.CORE.TOKEN_LEDGER
GROUP BY 1;
